data:
  build: docker/data
  hostname: data
  domainname: localdomain
  restart: always

postgres:
  build: docker/postgres
  hostname: postgres
  domainname: localdomain
  volumes_from:
    - data
  environment:
    - CKAN_PASS=ckan_pass
    - DATASTORE_PASS=datastore_pass
  restart: always

solr:
  build: docker/solr
  hostname: solr
  domainname: localdomain
  volumes:
    - ./_src/ckan/ckan/config/solr/schema.xml:/opt/solr/example/solr/ckan/conf/schema.xml
  restart: always

datapusher:
  build: _service-provider/_datapusher
  hostname: datapusher
  domainname: localdomain
  restart: always

ckan:
  build: .
  hostname: ckan
  domainname: localdomain
  ports:
    - "3003:80"
  links:
    - postgres:postgres
    - solr:solr
    - datapusher:datapusher
  command: /sbin/my_init --enable-insecure-key
  volumes_from:
    - data
  volumes:
    - ./_src:/usr/lib/ckan/default/src
    - ./_etc/ckan/custom_options.ini:/etc/ckan/default/custom_options.ini
    - ./_etc/supervisor/conf.d:/etc/supervisor/conf.d
  restart: always
  
