#!/bin/sh
set -eu
mkdir -p "${CKAN_DATA}/storage/uploads/group"
# run the init script in case the database need to be upgraded
"$CKAN_HOME"/bin/paster --plugin=ckan db init -c "${CKAN_CONFIG}/ckan.ini"
